#!/bin/bash
curl -O -k https://raw.github.com/pypa/virtualenv/master/virtualenv.py;
python virtualenv.py env;
env/bin/easy_install crepo;
rm virtualenv.*;
ln -s applications/go/go;
cd applications;
../env/bin/crepo sync;
cd ../configurations;
../env/bin/crepo sync;
cd ..;
./go install;
